name: Build

# Triggers the workflow on push or pull request events (for any branch in a repository)
on: [ push, pull_request ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.56.1 # MSVR
          - stable
          - nightly
    steps:
      - uses: actions/checkout@v2
      # Important preparation step: override the latest default Rust version in GitHub CI
      # with the current value of the iteration in the "strategy.matrix.rust"-array.
      - uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Check
        run: cargo check --all-targets --verbose --all-features
      - name: Build
        run: cargo build --all-targets --verbose --all-features
      - name: Run tests
        run: cargo test --all-targets --verbose --all-features

  build_nostd:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.56.1 # MSVR
          - stable
          - nightly
    steps:
      - uses: actions/checkout@v2
      # Important preparation step: override the latest default Rust version in GitHub CI
      # with the current value of the iteration in the "strategy.matrix.rust"-array.
      - uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: ${{ matrix.rust }}
          # some no_std target
          target: thumbv7em-none-eabihf
          override: true
      - name: Build
        run: cargo build --no-default-features --verbose --target thumbv7em-none-eabihf

  style_checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
    steps:
      - uses: actions/checkout@v2
      # Important preparation step: override the latest default Rust version in GitHub CI
      # with the current value of the iteration in the "strategy.matrix.rust"-array.
      - uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Rustfmt
        run: cargo fmt -- --check
      - name: Clippy
        run: cargo clippy --all-targets --all-features
      - name: Rustdoc
        run: cargo doc --all-features
